export const leftSidePriceSelection = [
    {
      name: "blank",
      code: "blank",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Large/Medium",
      code: "large/Medium",
      isTwoPrice: true,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Twister0Up",
      code: "twisterOup",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "21oz",
      code: "21oz",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "12oz",
      code: "12oz",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Medium",
      code: "medium",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "2Medium",
      code: "2medium",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Re Fill",
      code: "refill",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "BlankLine",
      code: "blankLine",
      isTwoPrice: true,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "21oz/12oz",
      code: "21oz/12oz",
      isTwoPrice: true,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Large",
      code: "large",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "2 For",
      code: "2for",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "300Ml",
      code: "300ml",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "500Ml",
      code: "500ml",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Test",
      code: "test",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
  ];

  export const rightSidePriceSelection = [
    {
      name: "blank",
      code: "blank",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Large/Medium",
      code: "large/Medium",
      isTwoPrice: true,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Twister0Up",
      code: "twisterOup",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "21oz",
      code: "21oz",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "12oz",
      code: "12oz",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Medium",
      code: "medium",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "2Medium",
      code: "2medium",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Re Fill",
      code: "refill",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "BlankLine",
      code: "blankLine",
      isTwoPrice: true,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "21oz/12oz",
      code: "21oz/12oz",
      isTwoPrice: true,
      quantity: null,
      currency: null,
      price: null,
    },

    {
      name: "Large",
      code: "large",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "2 For",
      code: "2for",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "300Ml",
      code: "300ml",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "500Ml",
      code: "500ml",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
    {
      name: "Test",
      code: "test",
      isTwoPrice: false,
      quantity: null,
      currency: null,
      price: null,
    },
  ];